baseURL = "https://soxfox.me/"
languageCode = "en-us"
title = "soxfox"
timeZone = "Australia/Melbourne"

[markup.highlight]
style = "github-dark"

[markup.tableOfContents]
startLevel = 1
endLevel = 1
